DROP DATABASE IF EXISTS user_data;
CREATE DATABASE user_data;

USE user_data;

CREATE TABLE venues(
  id INT NOT NULL PRIMARY KEY AUTOINCREMENT,
  venue_name VARCHAR(30) NOT NULL,
  capacity INT NOT NULL,
);


